#!/bin/bash

########################################################################
#  A simple utility to allow listening to digitally imported from CLI
#
#  by Steven Saus
#
#  Licensed under a Creative Commons BY-SA 3.0 Unported license
#  To view a copy of this license, visit http://creativecommons.org/licenses/by-sa/3.0/.
#
########################################################################

########################################################################
# Declarations
########################################################################

TEMPDIR=$(mktemp -d)
touch $TEMPDIR/tempjson.json
touch $TEMPDIR/tempkey.txt
touch $TEMPDIR/tempname.txt
touch $TEMPDIR/tempdesc.text
touch $TEMPDIR/stationtemp.text
TEMPJSON="$TEMPDIR/tempjson.json"
TEMPKEY="$TEMPDIR/tempkey.txt"
TEMPNAME="$TEMPDIR/tempname.txt"
TEMPDESC="$TEMPDIR/tempdesc.text"
TEMPSTATION="$TEMPDIR/stationtemp.text"
TermWidth=$(tput cols)


#get userkey
userkey=$(head -1 $HOME/.config/diuserkey.rc)

if [ -f $(which fzf) ];then
    pick_bin=$(which fzf)
else
    pick_bin=$(which pick)
fi
if [ -f $(which mplayer) ];then
    mplayer_bin=$(which mplayer)
else
    mplayer_bin=$(which mpv)
fi



#get channel list
VarA=$(curl https://www.zenradio.com | awk -F "di.app.start" '{ print $2 }' | grep -e ")" )
VarA=${VarA#?}
VarA=${VarA%??}
echo "$VarA" > "$TEMPJSON"
OLDIFS=$IFS
IFS=''

#parse channel list
cat "$TEMPJSON" | jq -r -M '.channels[] | .name' > $TEMPNAME
readarray -t NameArr < $TEMPNAME

cat "$TEMPJSON" | jq -r -M '.channels[] | .description' > $TEMPDESC
readarray -t DescArr < $TEMPDESC

cat "$TEMPJSON" | jq -r -M '.channels[] | .key' > $TEMPKEY
readarray -t KeyArr < $TEMPKEY
IFS=$OLDIFS

channels=${#KeyArr[@]}
# use for loop read all stations
for (( i=0; i<${channels}; i++ ));
do  
  size=${#KeyArr[$i]}
  size=$((size + 1))
  spacing=$((TermWidth - size))
  display1=$(echo "${NameArr[$i]} : ${DescArr[$i]}" | cut -c 1-${spacing} )
  echo "$display1:${KeyArr[$i]}" >> $TEMPSTATION
done

stationname=$(cat $TEMPSTATION | ${pick_bin} | awk -F ":" '{print $3}')
#echo "$stationname"


stationurl=$(echo "http://prem1.zenradio.com:80/$stationname?$userkey")
if [ "$1" == "--mpd" ]; then
    mpc add "$stationurl"
    Position=$(mpc playlist | wc -l )
    mpc play "$Position"
else
    if [ "$1" == "--url" ]; then
        echo "${stationurl}"
        exit 0
    else
        "${mplayer_bin}" -really-quiet "$stationurl" -user-agent "AudioAddict-di/3.2.0.3240 Android/5.1" &
        mplayer_PID=$!
        if [ -f $(which cava) ];then
            echo "Loading $stationname... quit cava to exit the stream."
            sleep 5
            export TERM=xterm-256color
            cava
        else
            echo "Listening to $stationname..."
            echo "Press any key to exit the stream."
            read
        fi
        kill -9 ${mplayer_PID}
    fi
fi


rm "$TEMPJSON"
rm "$TEMPKEY"
rm "$TEMPNAME"
rm "$TEMPDESC"
rm "$TEMPSTATION"
rmdir "$TEMPDIR"

